-- ============================================================
-- SOWT LMS — database setup
-- Paste this WHOLE file into Supabase → SQL Editor → Run.
-- You do not need to read or understand it. Just run it once.
-- ============================================================

-- 1) PROFILES: one row per person. New sign-ups start as 'pending'.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  whatsapp_number text,
  form_done boolean default false,
  role text not null default 'tutor' check (role in ('tutor','facilitator','admin')),
  status text not null default 'pending' check (status in ('pending','enrolled','revoked')),
  created_at timestamptz default now()
);

-- Auto-create a profile whenever someone signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name, whatsapp_number)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name',''), coalesce(new.raw_user_meta_data->>'whatsapp',''))
  on conflict (id) do nothing;
  return new;
end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users for each row execute function public.handle_new_user();

-- Stop tutors from making themselves admin/enrolled. Only admins change role/status.
create or replace function public.guard_profile_update()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is not null and not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    new.role := old.role;
    new.status := old.status;
  end if;
  return new;
end; $$;
drop trigger if exists profiles_guard on public.profiles;
create trigger profiles_guard before update on public.profiles
  for each row execute function public.guard_profile_update();

-- Small helpers used by the security rules
create or replace function public.is_admin() returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;
create or replace function public.is_staff() returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role in ('admin','facilitator')); $$;
create or replace function public.is_enrolled() returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and status = 'enrolled'); $$;

-- 2) SESSIONS (the curriculum)
create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  sort int default 0, week text, theme text, title text, description text,
  objectives text[] default '{}', activity text, facilitator text, session_date text,
  recording_url text, is_open boolean default false, assignments_active boolean default false
);

-- 3) ASSIGNMENTS
create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  session_id bigint references public.sessions(id) on delete cascade,
  title text, prompt text
);

-- 4) SUBMISSIONS (a tutor's answer + AI/facilitator feedback)
create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint references public.assignments(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  content text, feedback text, status text default 'new',
  created_at timestamptz default now(),
  unique (assignment_id, user_id)
);

-- 5) ANNOUNCEMENTS
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  author_name text, author_role text, title text, body text,
  created_at timestamptz default now()
);

-- 6) Turn on security (Row-Level Security)
alter table public.profiles enable row level security;
alter table public.sessions enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;
alter table public.announcements enable row level security;

-- PROFILES
drop policy if exists p_sel_own on public.profiles;
create policy p_sel_own on public.profiles for select using (id = auth.uid() or public.is_staff());
drop policy if exists p_upd on public.profiles;
create policy p_upd on public.profiles for update using (id = auth.uid() or public.is_admin());

-- SESSIONS
drop policy if exists s_sel on public.sessions;
create policy s_sel on public.sessions for select using (public.is_enrolled() or public.is_staff());
drop policy if exists s_all on public.sessions;
create policy s_all on public.sessions for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists s_upd_staff on public.sessions;
create policy s_upd_staff on public.sessions for update using (public.is_staff()) with check (public.is_staff());

-- ASSIGNMENTS
drop policy if exists a_sel on public.assignments;
create policy a_sel on public.assignments for select using (public.is_enrolled() or public.is_staff());
drop policy if exists a_all on public.assignments;
create policy a_all on public.assignments for all using (public.is_staff()) with check (public.is_staff());

-- SUBMISSIONS
drop policy if exists sub_sel on public.submissions;
create policy sub_sel on public.submissions for select using (user_id = auth.uid() or public.is_staff());
drop policy if exists sub_ins on public.submissions;
create policy sub_ins on public.submissions for insert with check (user_id = auth.uid());
drop policy if exists sub_upd on public.submissions;
create policy sub_upd on public.submissions for update using (user_id = auth.uid() or public.is_staff());

-- ANNOUNCEMENTS
drop policy if exists an_sel on public.announcements;
create policy an_sel on public.announcements for select using (public.is_enrolled() or public.is_staff());
drop policy if exists an_ins on public.announcements;
create policy an_ins on public.announcements for insert with check (public.is_staff());

-- 7) Seed the 10 sessions (you can edit all of this later, inside the app)
insert into public.sessions (sort,week,theme,title,description,objectives,activity,facilitator,session_date,is_open,assignments_active) values
(1,'Week 1','Foundation & Identity','Global Tutor Identity & Online Class Readiness','Set up your professional identity and get class-ready.',array['Define your tutor niche','Set up a professional online space'],'Introduce yourself as a tutor in 60 seconds.','Ms. Favor','Tue 5 Aug',true,true),
(2,'Week 1','Foundation & Identity','Essential Tech Tools for Online Tutoring','The core tools every online tutor needs.',array['Choose your core tool stack','Run a smooth online session'],'Explore one new teaching tool and note how you would use it.','Mr. Hammed S.K.','Thu 7 Aug',true,true),
(3,'Week 2','Leveraging AI','Leveraging AI in Your Tutoring','Use AI to plan and personalise faster.',array['Generate materials with AI','Personalise for each student'],'Build an AI prompt kit for your subject.','Mr. Hammed S.K.','Tue 12 Aug',true,true),
(4,'Week 2','Leveraging AI','Curriculum Navigation & Diagnostics','Map curricula and diagnose gaps.',array['Navigate UK/US curricula','Design a diagnostic'],'Create a short diagnostic for a level you teach.','Mr. Hammed S.K.','Thu 14 Aug',true,true),
(5,'Week 3','Pedagogy & Psychology','Online Pedagogy & Student Psychology','Teach and engage effectively online.',array['Apply online teaching methods','Support student confidence'],'Plan how you would teach one tricky topic online.','Ms. Taiwo','Tue 19 Aug',false,false),
(6,'Week 3','Pedagogy & Psychology','Professionalism, Ethics & Safeguarding','Conduct, ethics and keeping students safe.',array['Apply safeguarding basics','Act professionally online'],'Write your own code of conduct.','Ms. Taiwo','Thu 21 Aug',false,false),
(7,'Week 4','Client Relations & Business','Parent & Client Management','Win and keep happy clients.',array['Handle parent conversations','Give useful progress updates'],'Draft a parent progress update.','Ms. Favor','Tue 26 Aug',false,false),
(8,'Week 4','Client Relations & Business','Business Setup','Set up your tutoring as a business.',array['Set your pricing','Create simple contracts'],'Draft your pricing and a one-line offer.','Ms. Favor','Thu 28 Aug',false,false),
(9,'Week 5','Landing Gigs & Wellbeing','Landing Your First Gig','Find and close your first students.',array['Find leads','Run a discovery call'],'Write a first outreach message.','Ms. Taiwo','Tue 2 Sep',false,false),
(10,'Week 5','Landing Gigs & Wellbeing','Micro-Teaching & Wellbeing','Practise teaching and stay well.',array['Deliver a micro-lesson','Protect your energy'],'Record a 3-minute micro-lesson.','Ms. Taiwo','Thu 4 Sep',false,false);

-- one starter assignment per session
insert into public.assignments (session_id, title, prompt)
select id, 'Session '||sort||' assignment', 'Complete the task for this session and submit your answer for feedback.'
from public.sessions;

-- ============================================================
-- Added features: Q&A, Attendance, Certificate
-- ============================================================
create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  author_name text, author_role text default 'Tutor', body text,
  created_at timestamptz default now()
);
create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint references public.questions(id) on delete cascade,
  author_name text, author_role text, body text,
  created_at timestamptz default now()
);
alter table public.questions enable row level security;
alter table public.answers enable row level security;
drop policy if exists q_sel on public.questions;
create policy q_sel on public.questions for select using (public.is_enrolled() or public.is_staff());
drop policy if exists q_ins on public.questions;
create policy q_ins on public.questions for insert with check (public.is_enrolled() or public.is_staff());
drop policy if exists ans_sel on public.answers;
create policy ans_sel on public.answers for select using (public.is_enrolled() or public.is_staff());
drop policy if exists ans_ins on public.answers;
create policy ans_ins on public.answers for insert with check (public.is_enrolled() or public.is_staff());

create table if not exists public.attendance (
  session_id bigint references public.sessions(id) on delete cascade,
  tutor_id uuid references public.profiles(id) on delete cascade,
  present boolean default true,
  primary key (session_id, tutor_id)
);
alter table public.attendance enable row level security;
drop policy if exists att_sel on public.attendance;
create policy att_sel on public.attendance for select using (tutor_id = auth.uid() or public.is_staff());
drop policy if exists att_ins on public.attendance;
create policy att_ins on public.attendance for insert with check (public.is_staff());
drop policy if exists att_upd on public.attendance;
create policy att_upd on public.attendance for update using (public.is_staff()) with check (public.is_staff());
drop policy if exists att_del on public.attendance;
create policy att_del on public.attendance for delete using (public.is_staff());

alter table public.profiles add column if not exists certificate_code text;
alter table public.profiles add column if not exists certificate_name text;

-- Certificate admin override
alter table public.profiles add column if not exists certificate_unlocked boolean default false;
create or replace function public.guard_profile_update()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is not null and not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    new.role := old.role;
    new.status := old.status;
    new.certificate_unlocked := old.certificate_unlocked;
  end if;
  return new;
end; $$;

-- Session time + Resources
alter table public.sessions add column if not exists session_time text default '7:00 PM WAT';
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text, url text, description text, sort int default 0,
  created_at timestamptz default now()
);
alter table public.resources enable row level security;
drop policy if exists res_sel on public.resources;
create policy res_sel on public.resources for select using (public.is_enrolled() or public.is_staff());
drop policy if exists res_all on public.resources;
create policy res_all on public.resources for all using (public.is_admin()) with check (public.is_admin());

-- Batch 1: session_time + resources table
alter table public.sessions add column if not exists session_time text default '7:00 PM WAT';
create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text, url text, description text, sort int default 0,
  created_at timestamptz default now()
);
alter table public.resources enable row level security;
drop policy if exists res_sel on public.resources;
create policy res_sel on public.resources for select using (public.is_enrolled() or public.is_staff());
drop policy if exists res_all on public.resources;
create policy res_all on public.resources for all using (public.is_admin()) with check (public.is_admin());

-- Live class URL per session
alter table public.sessions add column if not exists live_class_url text;

-- Recording passcode
alter table public.sessions add column if not exists recording_passcode text;
